### ISSUE TITLE
[bug] Bug in function rotate_psi() in utils.training_statistics.py

### ISSUE THREAD

**Issue by sindhura97** [PIQuIL/QuCumber#89]
I got this error trace while trying to train a complex RBM with 8 visible and 8 hidden nodes using measurements from an 8-qubit system.
************************************************************************************************************
Traceback (most recent call last):

  File "<ipython-input-2-5c4d04ebf34a>", line 1, in <module>
    runfile('/home/1ot/Desktop/ground_state_computation/qucu_train_rbm/train_rbm.py', wdir='/home/1ot/Desktop/ground_state_computation/qucu_train_rbm')

  File "/home/1ot/anaconda3/envs/venv/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/1ot/anaconda3/envs/venv/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/1ot/Desktop/ground_state_computation/qucu_train_rbm/train_rbm.py", line 58, in <module>
    callbacks=callbacks)

  File "/home/1ot/anaconda3/envs/venv/lib//python3.7/site-packages/qucumber/nn_states/complex_wavefunction.py", line 350, in fit
    **kwargs

  File "/home/1ot/anaconda3/envs/venv/lib//python3.7/site-packages/qucumber/nn_states/wavefunction.py", line 526, in fit
    callbacks.on_epoch_end(self, ep)

  File "/home/1ot/anaconda3/envs/venv/lib//python3.7/site-packages/qucumber/callbacks/callback_list.py", line 71, in on_epoch_end
    cb.on_epoch_end(rbm, epoch)

  File "/home/1ot/anaconda3/envs/venv/lib//python3.7/site-packages/qucumber/callbacks/metric_evaluator.py", line 133, in on_epoch_end
    val = metric_fn(nn_state, **self.metric_kwargs)

  File "/home/1ot/anaconda3/envs/venv/lib//python3.7/site-packages/qucumber/utils/training_statistics.py", line 223, in KL
    psi_r = rotate_psi(nn_state, bases[b], space, unitary_dict)

  File "/home/1ot/anaconda3/envs/venv/lib//python3.7/site-packages/qucumber/utils/training_statistics.py", line 85, in rotate_psi
    psi_r[:, slc] = cplx.matmul(m, U)

  File "/home/1ot/anaconda3/envs/venv/lib//python3.7/site-packages/qucumber/utils/cplx.py", line 108, in matmul
    z[0] = torch.mv(x[0], y[0]) - torch.mv(x[1], y[1])

RuntimeError: size mismatch, [2 x 2], [8] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:842

*******************************************************************************************************

The function rotate_psi() tries to multiply matrices of incompatibile sizes.
line 81: slc is of length N
line 82: U is of length N
line 83: multiplies m with U 

'm' is a complex 2x2 matrix while 'U' is a complex vector of length N.

This method thus threw me an error when I had N=8 i.e; an 8 qubit system.

**Comment by emerali** [comment]
I don't seem to be able to reproduce this bug, so I'll need some more details.

From your stack trace I noticed the following:
```
TypeError: mul(): argument 'other' (position 1) must be Tensor, not complex
```

There shouldn't be anything of complex type reaching the `rotate_psi` function. Are you passing parameters of the proper type? For example, have the unitaries you provided been converted to torch tensors using the proper scheme? i.e. an m-by-n complex matrix would be represented by a tensor of shape (2, m, n) with the 0th entry being the real part and the 1st entry being the imaginary part.

**Comment by sindhura97** [comment]
I am sorry, I posted the wrong stack trace, I edited it now.

**Comment by emerali** [comment]
Alright, so I believe I've found the bug and fixed it. The update is currently being built and will be pushed in about 10 minutes. 

Once that's done, try installing the updated version of QuCumber using `pip install -U qucumber` and re-running your code. The new version of QuCumber is 1.2.1, so you could try printing out `qucumber.__version__` if you're unsure whether the update installed properly.
